name: Generate Language Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs automatically every night at midnight
  workflow_dispatch: # Allows you to run it manually

# This is the new part that gives it permission to save the image!
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 5
